### ISSUE TITLE
Kako pogledam loge?

### ISSUE THREAD

**Issue by marksev1** [andrejs2/arso_potresi#3]
Živjo, piše neznano v potresi senzorju stalno. Kako pogledam kaj je narobe?

**Comment by andrejs2** [comment]
Tole daš v `configuration.yaml`:
```
logger:
  default: info
  logs:
    custom_components.arso_potresi: debug
```
